site_name: 'Memoria - Práctica 2'

theme:
  name: material
  author: 'authors.md'
  language: es
  features:
    - navigation.indexes
    - navigation.footer  

nav:
  - Ejercicio grupal: 'ejerciciogrupal.md'

plugins:
  - search
  - with-pdf:
      output_path: ../../memoria.pdf
      toc_title: 'Índice'
      cover_subtitle: 'Miguel Ángel Pérez Olivencia, 
                      Brandon René Morales Viracocha, 
                      Gonzalo Morato de Tapia Caro, 
                      Ángela Poyatos Gómez'
      author: 'Desarrollo de Software'
      copyright: '3º Ingeniería Informática - 2023/2024'

extra_css:
  - styles.css

markdown_extensions:
  - md_in_html